// src/components/ExportButtons.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { Copy, Download, Check } from 'lucide-vue-next';
import type { ExportData } from '@/types/batch';

const props = defineProps<{
  exportData: ExportData;
}>();

const copied = ref(false);

const jsonString = computed(() => JSON.stringify(props.exportData, null, 2));

const handleCopy = async () => {
  try {
    await navigator.clipboard.writeText(jsonString.value);
    copied.value = true;
    setTimeout(() => copied.value = false, 2000);
    // Simple notification can be handled by parent or just omitted
  } catch (error) {
    console.error('Failed to copy', error);
  }
};

const handleDownload = () => {
  const blob = new Blob([jsonString.value], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `ocr-result-${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
</script>

<template>
  <div class="flex items-center gap-2">
    <button
      type="button"
      @click="handleCopy"
      class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-3 gap-2"
    >
      <Check v-if="copied" class="h-4 w-4" />
      <Copy v-else class="h-4 w-4" />
      {{ copied ? "已複製" : "Copy JSON" }}
    </button>
    <button
      type="button"
      @click="handleDownload"
      class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-3 gap-2"
    >
      <Download class="h-4 w-4" />
      Download JSON
    </button>
  </div>
</template>

// src/components/ExportButtons.tsx
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { ExportData } from "@/types/batch";

interface ExportButtonsProps {
  exportData: ExportData;
}

export function ExportButtons({ exportData }: ExportButtonsProps) {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  const jsonString = JSON.stringify(exportData, null, 2);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(jsonString);
      setCopied(true);
      toast({
        title: "已複製",
        description: "JSON 已複製到剪貼簿",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: "複製失敗",
        description: "請手動複製",
        variant: "destructive",
      });
    }
  };

  const handleDownload = () => {
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ocr-result-${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "下載成功",
      description: "JSON 檔案已下載",
    });
  };

  return (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopy}
        className="gap-2"
      >
        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
        {copied ? "已複製" : "Copy JSON"}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleDownload}
        className="gap-2"
      >
        <Download className="h-4 w-4" />
        Download JSON
      </Button>
    </div>
  );
}
